name: Playwright Tests
on:
    push:
        branches: [main, master]
    schedule:
        - cron: "30 11 * * *"
    workflow_dispatch:
jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        env:
            EMAIL: ${{ secrets.EMAIL }}
            PASSWORD: ${{ secrets.PASSWORD }}
        steps:
            - name: Connect to Tailscale
              uses: tailscale/github-action@v2
              with:
                  authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

            - name: Connect to Tailscale with Exit Node
              run: |
                  tailscale up --exit-node=100.97.211.122

            - name: Check Tailscale connection
              run: tailscale status

            - name: prod accessibliity
              run: curl -I https://admin-portal.startree.cloud/overview

            - name: staging accessibliity
              run: curl -I https://admin-portal.startree-staging.cloud/overview

            - name: Check service accessibility
              id: check_service
              run: |
                  STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}" https://admin-portal.startree-dev.cloud/overview)
                  echo "Status Code: $STATUS_CODE"
                  if [ "$STATUS_CODE" -ne 200 ]; then
                    echo "Service is not accessible (HTTP $STATUS_CODE)"
                    exit 1
                  fi

            # Only run these steps if the previous step succeeded (service is accessible)
            - uses: actions/checkout@v4
              if: success()
            - uses: actions/setup-node@v4
              with:
                  node-version: lts/*
              if: success()

            - name: Install dependencies
              run: npm ci
              if: success()

            - name: Install Playwright Browsers
              run: npx playwright install --with-deps
              if: success()

            - name: Run Playwright tests
              run: npx playwright test
              if: success()

            - uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: playwright-report
                  path: playwright-report/
                  retention-days: 30
